### ISSUE TITLE
`agender roll` is picked up as `gender roll`

### ISSUE THREAD

**Issue by inklesspen** [inklesspen/genderrolls#3]
Because substrings, of course. Simplest solution is to use regexps to require either `^| ` at the beginning and `$| ` at the end.

**Comment by hypatian** [comment]
Probably you want the "\b" "word break" match.

**Comment by rbxbx** [comment]
Desired behavior is to not match at all at this point?

**Comment by inklesspen** [comment]
@rbxbx yeah, input text of `agender roll` should not match the `gender roll` trigger.

The `\b` regex special character is likely to be helpful here; that will also help with the `fenby` vs `enby` issue.

**Comment by inklesspen** [comment]
@hypatian turns out `\b` won't work, because `+` and `-` aren't recognized as word characters.
